name: trekon
description: A new Flutter project for trekking adventures.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Matches Flutter 3.29

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Updated for Flutter 3.29
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"